services:
  postgres:
    image: postgres:16-alpine
    container_name: takapedia-postgres
    environment:
      POSTGRES_USER: takapedia
      POSTGRES_PASSWORD: takapedia_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
