version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres-takapedia-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpass
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
