version: '3.8'
name: takapedia
volumes:
  keycloak_data:
  pg_data:

services:
  postgres:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - takapedia-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - takapedia-network

  config-server:
    container_name: config-server
    build:
      context: ../
      dockerfile: config-server/Dockerfile
    image: config-server:latest
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - takapedia-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  service-registry:
    container_name: service-registry
    build:
      context: ../
      dockerfile: service-registry/Dockerfile
    image: service-registry:latest
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_ENVIRONMENT=dev
    networks:
      - takapedia-network

  api-gateway:
    container_name: api-gateway
    build:
      context: ../
      dockerfile: api-gateway/Dockerfile
    image: api-gateway:latest
    ports:
      - "80:80"
    depends_on:
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_URI=http://service-registry:8761/eureka
      - CONFIG_SERVER_URI=http://config-server:8888
    networks:
      - takapedia-network

  authentication-service:
    container_name: authentication-service
    build:
      context: ../
      dockerfile: authentication-service/Dockerfile
    image: authentication-service:latest
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
      service-registry:
          condition: service_started
      api-gateway:
          condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CONFIG_URI=http://config-server:8888
      - EUREKA_URI=http://service-registry:8761/eureka
    networks:
      - takapedia-network

networks:
  takapedia-network:
    driver: bridge
