spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${services.auth.url}
              predicates:
                - Path=/api/v1/auth/**

services:
  auth:
    url: http://localhost:8081