apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: kaniko
spec:
  containers:
    - name: maven
      image: maven:3.9-eclipse-temurin-21-alpine
      command:
        - cat
      tty: true
      volumeMounts:
        - name: maven-cache
          mountPath: /root/.m2
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command: []
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: maven-cache
      emptyDir: {}
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
